services:
  - type: web
    name: texta-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CUDA_VISIBLE_DEVICES
        value: ""
      - key: PYTORCH_CUDA_ALLOC_CONF
        value: "max_split_size_mb:128"
