services:
  - type: web
    name: texta-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn.conf.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
